sonar.projectKey=tcc-analysis
sonar.projectName=Analise TCC - Oscar e Artur

sonar.sources=.

sonar.java.binaries=.

sonar.host.url=http://localhost:9000
sonar.token=sqp_2e188a1ab54cfd814d4cadabbcba34ab84f0913a

sonar.sourceEncoding=UTF-8
